name: TorncraftUtils
main: lekro.bukkitplugins.torncraftutils.TorncraftPlugin
version: 0.0.3
commands:
    worldspawn:
        description: Teleports you to the spawn of the world you are currently in.
        usage: /worldspawn
        permission: torncraftutils.worldspawn
        permission-message: You can't do this!
    unbreakable:
        description: Makes the breakable tool in your hand unbreakable.
        usage: /unbreakable
        permission: torncraftutils.unbreakable
        permission-message: You can't do this!
    vote:
        description: Provides links for voting for Torncraft
        usage: /vote
        permission: torncraftutils.vote
        permission-message: What??? You can't vote!!! It's not for you!
permissions:
    torncraftutils.worldspawn:
        description: Allows you to use /worldspawn
        default: op
    torncraftutils.unbreakable:
        description: Allows you to use /unbreakable
        default: op
    torncraftutils.vote:
        description: Allows you to see links to vote
        default: true